import { useEffect, useState } from 'react';

import { fetchEvalReport } from './api.js';
import { parseReport } from './Report.js';
import { Mark } from './ui.js';
import { linkTo } from './router.js';
import './landing.css';

/**
 * The overview page, at `/`.
 *
 * It exists because the README's first line is a live link and the first reader
 * is plausibly an automated screener. A link that opens straight into a review
 * queue proves the thing runs but says nothing about what it is; this page says
 * what it is in about fifteen seconds and then gets out of the way.
 *
 * The one rule it follows, which is the reason it is worth having at all: **no
 * number on this page is written by hand.** The metrics table is the `Headline`
 * section of the committed `eval/results.md`, selected and rendered verbatim by
 * the same parser the eval page uses. Selecting a section is not computing one,
 * so P4.2's invariant survives -- there is still exactly one place a number can
 * be wrong, and it is the report. If the report changes, this page changes with
 * it; if the report is missing, this page says so rather than showing a stale
 * figure it remembered.
 */
export function Landing() {
  return (
    <div className="landing">
      <Hero />
      <Metrics />
      <Thesis />
      <Trust />
      <NotAI />
      <Foot />
    </div>
  );
}

/* --------------------------------------------------------------- hero -- */

function Hero() {
  return (
    <header className="hero">
      <div className="wrap">
        <a className="brand brand-lg" {...linkTo('landing')}>
          <Mark size={13} />
          Praman
        </a>

        <p className="eyebrow">Defense-only dispute evidence responder</p>

        <h1>
          Agentic evidence has to be captured at transaction time,
          <em> because by dispute time it is gone.</em>
        </h1>

        <p className="lede">
          Praman reads a dispute in Razorpay&rsquo;s documented Disputes API schema, assembles
          the evidence a merchant actually holds, decides contest-or-abstain through a
          deterministic sufficiency gate, drafts a contest mapped to Razorpay&rsquo;s typed
          evidence fields, and submits only through a human approving that specific dispute.
        </p>

        <div className="cta">
          <a className="btn primary" {...linkTo('console')}>
            Open the review console
          </a>
          <a className="btn" {...linkTo('eval')}>
            Read the eval results
          </a>
        </div>

        <p className="cta-note">
          The console runs on seeded, simulated data and says so on every screen. No live
          Razorpay call is ever made.
        </p>
      </div>
    </header>
  );
}

/* ------------------------------------------------------------ metrics -- */

/**
 * The headline table, lifted verbatim out of the committed eval report.
 *
 * It finds the `Headline` heading and renders the first table under it. No
 * arithmetic, no rounding, no reformatting of a single cell -- if this page and
 * `eval/results.md` ever disagree, that is a bug in the parser rather than a
 * second set of numbers drifting from the first.
 */
function Metrics() {
  const [table, setTable] = useState<{ header: string[]; rows: string[][] } | null>(null);
  const [failed, setFailed] = useState(false);

  useEffect(() => {
    fetchEvalReport()
      .then((markdown) => {
        const blocks = parseReport(markdown);
        const at = blocks.findIndex(
          (block) => block.kind === 'heading' && /^headline$/i.test(block.text.trim()),
        );
        const found = at === -1 ? undefined : blocks.slice(at + 1).find((b) => b.kind === 'table');
        if (found && found.kind === 'table') setTable({ header: found.header, rows: found.rows });
        else setFailed(true);
      })
      .catch(() => setFailed(true));
  }, []);

  return (
    <section className="band">
      <div className="wrap">
        <div className="band-head">
          <span className="label">Measured, not claimed</span>
          <h2>
            One dev corpus, one held-out set that is out-of-distribution by construction, and
            the shift between them reported whichever way it falls.
          </h2>
        </div>

        {failed ? (
          <p className="hint">
            The eval report could not be loaded. It is generated by <code>pnpm eval</code> and
            committed at <code>eval/results.md</code>; this page renders that file and computes
            nothing of its own, so an empty table here means the report is missing, never that
            the numbers differ.
          </p>
        ) : !table ? (
          <p className="hint">Loading the committed eval report&hellip;</p>
        ) : (
          <div className="metrics-scroll">
            <table className="metrics">
              <thead>
                <tr>
                  {table.header.map((cell, i) => (
                    <th key={i} className={i === 0 ? '' : 'num'}>
                      {cell}
                    </th>
                  ))}
                </tr>
              </thead>
              <tbody>
                {table.rows.map((row, r) => (
                  <tr key={r}>
                    {row.map((cell, c) => (
                      <td key={c} className={c === 0 ? 'metric-name' : 'num'}>
                        {cell}
                      </td>
                    ))}
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        )}

        <p className="provenance">
          Rendered verbatim from the committed <code>eval/results.md</code>. Model of record{' '}
          <code>qwen/qwen3.8-27b</code> via Groq, replayed from committed recordings —{' '}
          <code>pnpm eval</code> reproduces the file byte for byte with no network and no API
          key. Headline metrics are precision and recall against corpus labels and
          false-positive cost in rupees; no simulated outcome is reported as a result anywhere.
        </p>
      </div>
    </section>
  );
}

/* ------------------------------------------------------------- thesis -- */

/**
 * The capture argument, drawn rather than asserted.
 *
 * The filled squares are evidence the merchant still holds at dispute time; the
 * hollow one is evidence that lived with the agent platform and is gone. It is
 * the same mark as the wordmark, at size, which is the whole identity: the logo
 * IS the thesis.
 */
function Thesis() {
  return (
    <section className="band alt">
      <div className="wrap thesis">
        <div>
          <span className="label">The gap</span>
          <h2>
            The agent identifier, the mandate reference, the protocol metadata and the
            conversation trace live with the agent platform or the TPAP — not with the merchant.
          </h2>
          <p>
            Weeks or months later, when the dispute arrives, there is nothing to retrieve. So
            the transaction store <em>is</em> the capture layer, and{' '}
            <code>POST /evidence-pack</code> is that layer as a real endpoint rather than a box
            on a diagram — every one of the 100 seeded disputes was captured through it.
          </p>
          <p>
            <a
              href="https://razorpay.com/blog/agentic-payments-and-npci/"
              target="_blank"
              rel="noreferrer"
            >
              Razorpay and NPCI shipped agentic payments on UPI Reserve Pay
            </a>{' '}
            in February 2026, and that announcement is entirely about the consent going in. It
            says nothing about disputes, chargebacks, evidence, or merchant recourse when one of
            those payments is later challenged. Praman is about the other end.
          </p>
        </div>

        <figure className="capture">
          <div className="capture-row">
            <span className="label">At transaction time</span>
            <div className="chips">
              {['agent id', 'mandate ref', 'protocol meta', 'conversation'].map((k) => (
                <span className="chip-ev held" key={k}>
                  {k}
                </span>
              ))}
            </div>
          </div>
          <div className="capture-arrow" aria-hidden="true">
            <span>weeks pass</span>
          </div>
          <div className="capture-row">
            <span className="label">At dispute time, uncaptured</span>
            <div className="chips">
              {['agent id', 'mandate ref', 'protocol meta', 'conversation'].map((k) => (
                <span className="chip-ev gone" key={k}>
                  {k}
                </span>
              ))}
            </div>
          </div>
          <figcaption>
            Filled is evidence still held. Hollow is evidence that only ever existed at the
            moment of the transaction.
          </figcaption>
        </figure>
      </div>
    </section>
  );
}

/* -------------------------------------------------------------- trust -- */

const PROPERTIES = [
  {
    k: 'One door',
    d: 'The approve action in the review console is the only path to submission. Eval mode scores gate decisions and drafts and provably never touches the submission adapter — a test enforces it.',
  },
  {
    k: 'Abstention over bluffing',
    d: 'Insufficient evidence abstains with a stated reason. A bluffed contest that fails costs fees and handling time, and that is the false-positive cost the eval reports in rupees.',
  },
  {
    k: 'Deterministic gate',
    d: 'Required-evidence coverage, mandate arithmetic and anomaly signals decide contest-or-abstain. Thresholds are config, every rule is traced, and no model is consulted.',
  },
  {
    k: 'Append-only audit',
    d: 'Every state transition is recorded with its actor and timestamp. A human appears exactly once in the trail, at approval.',
  },
  {
    k: 'Schema fidelity',
    d: 'Dispute entities, typed evidence fields, contest payloads and error states mirror the documented Disputes API. The live docs are the authority; where they disagreed with our notes, the docs won three times.',
  },
  {
    k: 'Defense-only',
    d: 'Nothing offense-capable. The generator creates dispute scenarios, never attack tooling, and a transaction carrying fraud signals is not defended.',
  },
];

function Trust() {
  return (
    <section className="band">
      <div className="wrap">
        <div className="band-head">
          <span className="label">Would you trust it</span>
          <h2>The gates, the audit log and the determinism are the product, not decoration.</h2>
        </div>
        <div className="props">
          {PROPERTIES.map((p) => (
            <div className="prop" key={p.k}>
              <h3>{p.k}</h3>
              <p>{p.d}</p>
            </div>
          ))}
        </div>
      </div>
    </section>
  );
}

/* ------------------------------------------------------------- not AI -- */

/**
 * The section a screener rewards and a panelist probes for.
 *
 * It is on the landing page rather than only in the README because it is the
 * strongest single claim the project makes, and the one most likely to be
 * doubted if it has to be gone looking for.
 */
function NotAI() {
  return (
    <section className="band alt">
      <div className="wrap">
        <div className="band-head">
          <span className="label">Where we deliberately did not use AI</span>
          <h2>
            A money action must never depend on a stochastic step, and an eval must be
            reproducible.
          </h2>
        </div>

        <div className="boundary">
          <div className="side llm-side">
            <span className="label">A model does exactly three things</span>
            <ul>
              <li>Summarises a conversation trace</li>
              <li>Drafts the explanation letter</li>
              <li>Flags ambiguity for a human</li>
            </ul>
          </div>
          <div className="side det-side">
            <span className="label">Code does everything else</span>
            <ul>
              <li>Schema and evidence-field mapping</li>
              <li>Gate thresholds and the contest decision</li>
              <li>Metrics computation</li>
              <li>Submission — every step on the money path</li>
            </ul>
          </div>
        </div>

        <p className="provenance">
          The drafter can only ever <em>withhold</em> a contest, never create one, raise an
          amount, or submit — on the dev corpus it changed the outcome on 2 of 100 disputes, in
          the conservative direction only. Any model step that errors, times out, refuses, or
          returns output failing schema validation routes the dispute to abstain with{' '}
          <em>&ldquo;assembly failure, manual review required&rdquo;</em>, audit-logged and never
          silently retried. Claude Code built this repository; no agent loop runs inside Praman
          itself. It is in the build loop, not the money path.
        </p>
      </div>
    </section>
  );
}

/* --------------------------------------------------------------- foot -- */

function Foot() {
  return (
    <footer className="foot">
      <div className="wrap">
        <div className="foot-cta">
          <a className="btn primary" {...linkTo('console')}>
            Open the review console
          </a>
          <a className="btn" {...linkTo('eval')}>
            Read the eval results
          </a>
        </div>
        <p>
          Built for the Razorpay AI Buildathon, Track 2. Every dispute, payment and mandate in
          the demo is generated by a seeded simulator and labelled as simulated wherever it is
          rendered.
        </p>
      </div>
    </footer>
  );
}
