/**
 * P0.2: record 5 real Razorpay TEST-MODE `pay_` ids into a committed fixture.
 *
 * Why this shape. Razorpay's test mode will not mint a *captured* payment from
 * a pure server-side API call -- reaching captured state needs an order plus a
 * checkout, which is a browser flow. TASKS.md pre-approves the pragmatic route:
 * make the 5 payments by hand through the dashboard's test checkout, then run
 * this script to READ them back and record them. The `pay_` ids are the
 * deliverable; the elegance of the seeding is not.
 *
 * Usage:
 *   1. Dashboard (TEST mode) > make 5 payments via test checkout.
 *   2. Put RAZORPAY_KEY_ID / RAZORPAY_KEY_SECRET in .env
 *   3. pnpm tsx scripts/record-test-payments.ts
 *
 * This script only ever READS from Razorpay (GET /payments). It creates nothing
 * and mutates nothing.
 */
import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import process from 'node:process';

process.loadEnvFile?.('.env');

const KEY_ID = process.env.RAZORPAY_KEY_ID;
const KEY_SECRET = process.env.RAZORPAY_KEY_SECRET;
const REQUIRED = 5;

const OUT = fileURLToPath(
  new URL('../packages/core/src/fixtures/razorpay-test-payments.json', import.meta.url),
);

interface RazorpayPayment {
  id: string;
  amount: number;
  currency: string;
  status: string;
  method: string;
  captured: boolean;
  created_at: number;
}

async function main(): Promise<void> {
  if (!KEY_ID || !KEY_SECRET) {
    console.error('FAIL: RAZORPAY_KEY_ID / RAZORPAY_KEY_SECRET not set. See .env.example.');
    process.exit(1);
  }
  if (!KEY_ID.startsWith('rzp_test_')) {
    // Refusing a live key is not politeness, it is a guard: this project must
    // never touch a production Razorpay account.
    console.error(`FAIL: key id "${KEY_ID}" is not a test-mode key (expected rzp_test_ prefix).`);
    process.exit(1);
  }

  const auth = Buffer.from(`${KEY_ID}:${KEY_SECRET}`).toString('base64');
  const response = await fetch('https://api.razorpay.com/v1/payments?count=100', {
    headers: { authorization: `Basic ${auth}` },
  });

  if (!response.ok) {
    console.error(`FAIL: ${response.status} ${response.statusText}`);
    console.error((await response.text()).slice(0, 600));
    process.exit(1);
  }

  const body = (await response.json()) as { count: number; items: RazorpayPayment[] };
  const captured = body.items.filter((p) => p.status === 'captured');

  if (captured.length < REQUIRED) {
    console.error(
      `FAIL: found ${captured.length} captured test payment(s), need ${REQUIRED}.\n` +
        'Make the remaining ones through the dashboard test checkout, then re-run.',
    );
    process.exit(1);
  }

  // Oldest-first so the recorded set is stable as more test payments accumulate.
  const chosen = captured
    .sort((a, b) => a.created_at - b.created_at)
    .slice(0, REQUIRED)
    .map((p) => ({
      id: p.id,
      amount: p.amount,
      currency: p.currency,
      status: p.status,
      method: p.method,
      created_at: p.created_at,
    }));

  writeFileSync(
    OUT,
    `${JSON.stringify(
      {
        pending: false,
        source: 'Razorpay test mode, GET https://api.razorpay.com/v1/payments',
        key_id: KEY_ID,
        recorded_at: new Date().toISOString(),
        note: 'Real test-mode payment ids. Disputes generated by the simulator reference these.',
        payments: chosen,
      },
      null,
      2,
    )}\n`,
  );

  console.log(`OK: recorded ${chosen.length} test-mode payment ids to ${OUT}`);
  for (const p of chosen) console.log(`  ${p.id}  ${p.amount} ${p.currency}  ${p.method}`);
}

main().catch((error: unknown) => {
  console.error('FAIL: request threw.');
  console.error(error);
  process.exit(1);
});
